### PR TITLE
Snowball improvements

### PR DESCRIPTION
**Pull request by kevin-hsieh**

### CODE REVIEW

**Review by chihhungl — APPROVED** [review]

**Review by dafrenchyman — CHANGES_REQUESTED** [review]
I like the idea of missing and hitting other people by accident,.. but not hard-coding there names. Could we have the slack-bot get the names of everyone in the channel and randomly hit one of them?

**Comment by kevin-hsieh** [comment]
So currently we don't have any way to access who else is in the channel so no. But the reason I chose these two people is because 1 Stanley will be cool with it and 2 I don't want Stanley to be hit when it was meant for him. It's gotta be someone else. So I chose Yan Ting. If you don't like this specific feature I can remove it and remove the hit someone else altogether but I think we should still get the other 3 features in.

**Comment by kevin-hsieh** [comment]
In the mean time I've refactored this so that I extracted some of these as functions. This is to pave the road to have some stats saved in local storage. I am thinking of implementing a leader board for hits + accuracy %.

**Review by dafrenchyman — APPROVED** [review]
Alright,... for now I'll accept it :-)

**Pull request merged**
